### ISSUE TITLE
Push material metadata changes to website after edit

### ISSUE THREAD

**Issue by DrDrij** [econ-ark/econ-ark.org#58]
Since adding the 'Edit metadata' link in #57 it would be good for any changes to update immediately on the econ-ark.org website. They are currently set to update once daily.

**Comment by DrDrij** [comment]
Metadata files from REMARK and DemARK are copied over to the Econ-ark.org repository on "push" to markdown files directory.

The website is rebuilt immediately with the updated metadata.

https://github.com/econ-ark/REMARK/blob/b2f67ea5bb27c1c81d3d7d4a544f02bf8272a19d/.github/workflows/transfer-remark-metadata.yml#L3

```
name: Copy metadata
on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'

```
